import { StyleSheet } from 'react-native';
import colors from '../../../theme/colors';

const mfaStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  keyboardView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.backgroundSecondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
  },
  headerPlaceholder: {
    width: 40,
  },
  content: {
    padding: 24,
    alignItems: 'center',
  },
  iconWrap: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.backgroundSecondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  iconWrapDestructive: {
    backgroundColor: colors.logoutBackground,
  },
  iconWrapSmall: {
    alignSelf: 'center',
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.backgroundSecondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  inputSection: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 16,
    alignSelf: 'flex-start',
  },
  digitRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
    justifyContent: 'center',
  },
  digitBox: {
    width: 44,
    height: 56,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.backgroundSecondary,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '700',
    color: colors.primary,
  },
  digitFilled: {
    borderColor: colors.primary,
  },
  digitError: {
    borderColor: colors.danger,
    backgroundColor: colors.logoutBackground,
  },
  criticalBox: {
    width: '100%',
    backgroundColor: colors.logoutBackground,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.danger,
  },
  criticalText: {
    fontSize: 13,
    color: colors.danger,
    marginBottom: 12,
    lineHeight: 18,
  },
  criticalInput: {
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  criticalInputSuccess: {
    borderColor: colors.success,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.logoutBackground,
    borderRadius: 12,
    padding: 12,
    marginBottom: 20,
    width: '100%',
  },
  errorText: {
    flex: 1,
    fontSize: 13,
    color: colors.danger,
    marginLeft: 8,
  },
  verifyBtn: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    width: '100%',
    elevation: 2,
    shadowColor: colors.shadowCard || '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  verifyBtnDisabled: {
    backgroundColor: colors.disabledButton,
    elevation: 0,
  },
  verifyBtnText: {
    color: colors.textWhite || '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  googleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 16,
    backgroundColor: colors.backgroundSecondary,
    width: '100%',
    marginTop: 20,
  },
  googleText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
    marginLeft: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay || 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  authScreen: {
    backgroundColor: colors.backgroundSecondary,
    minHeight: '60%',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.primary,
    marginBottom: 10,
    textAlign: 'center',
  },
  modalSub: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  authError: {
    fontSize: 13,
    color: colors.danger,
    textAlign: 'center',
    marginBottom: 12,
  },
  backBtn: {
    alignItems: 'center',
    paddingVertical: 15,
  },
  backText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: '600',
  },
});

export default mfaStyles;
